services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "${LAN_IP}:53:53/tcp"
      - "${LAN_IP}:53:53/udp"
      - "${LAN_IP}:8081:80/tcp"
    environment:
      TZ: "America/Los_Angeles"
      FTLCONF_webserver_api_password: "${PIHOLE_WEBPASSWORD}"
      FTLCONF_dns_listeningMode: "ALL"
    volumes:
      - "/data/docker/appdata/pihole/etc-pihole:/etc/pihole"
    cap_add:
      - SYS_NICE
    restart: unless-stopped
