services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    user: "1000:1001"
    environment:
      - TZ=America/Los_Angeles
    networks:
      - media-network
    volumes:
      - /data/docker/appdata/komga/config:/config
      - /data/docker/appdata/komga/tmp:/tmp
      - /data/media/manga:/data/manga
      - /data/media/books:/data/media/books
    ports:
      - "${LAN_IP}:25600:25600"
    restart: unless-stopped
    mem_limit: 1g

networks:
  media-network:
    external: true
