configure_data_disk() {
  local index="$1"
  local disk="$2"
  local label="$3"
  local mountpoint="/mnt/disk$index"
  local active_mountpoint
  active_mountpoint="$(active_mount_path "$mountpoint")"

  if is_placeholder "$disk"; then
    if [[ "$APPLY" == true ]]; then
      die "refusing placeholder data disk for disk$index"
    fi
    warn "Would refuse placeholder data disk for disk$index: $disk"
    return 0
  fi

  ensure_safe_mountpoint "$active_mountpoint"
  if ! filesystem_matches "$disk" btrfs "$label"; then
    confirm_destructive "About to format data disk $index as btrfs." "$disk"
    run mkfs.btrfs -f -L "$label" "$disk"
  fi

  log "+ mountpoint -q $(printf '%q' "$active_mountpoint")"
  if [[ "$APPLY" == true ]] && mountpoint -q "$active_mountpoint"; then
    run mount -o "remount,$BTRFS_DATA_MOUNT_OPTS" "$active_mountpoint"
  elif [[ "$APPLY" == true ]]; then
    run mount -o "$BTRFS_DATA_MOUNT_OPTS" "$disk" "$active_mountpoint"
  fi

  ensure_dir "$active_mountpoint/pool"
  ensure_dir "$active_mountpoint/snapshots"
  run chown "$PUID:$PGID" "$active_mountpoint/pool"
  run chmod 0775 "$active_mountpoint/pool"
  local subvol
  for subvol in "${POOL_SUBVOLUMES[@]}"; do
    if [[ -d "$active_mountpoint/pool/$subvol" ]]; then
      run chown "$PUID:$PGID" "$active_mountpoint/pool/$subvol"
      run chmod 0775 "$active_mountpoint/pool/$subvol"
      continue
    fi
    run btrfs subvolume create "$active_mountpoint/pool/$subvol"
    run chown "$PUID:$PGID" "$active_mountpoint/pool/$subvol"
    run chmod 0775 "$active_mountpoint/pool/$subvol"
  done
  # torrents lives inside media for hardlink compatibility with arr stack
  ensure_dir "$active_mountpoint/pool/media/torrents"
  run chown "$PUID:$PGID" "$active_mountpoint/pool/media/torrents"
  run chmod 2775 "$active_mountpoint/pool/media/torrents"
  ensure_torrents_symlink "$active_mountpoint/pool"
}

ensure_torrents_symlink() {
  local pool_path="$1"
  if [[ -L "$pool_path/torrents" ]] && [[ "$(readlink "$pool_path/torrents")" == "media/torrents" ]]; then
    return 0
  fi
  if [[ -e "$pool_path/torrents" ]]; then
    die "$pool_path/torrents exists but is not the expected media/torrents symlink"
  fi
  run ln -s media/torrents "$pool_path/torrents"
}

generate_fstab_text() {
  printf '# Generated by bootstrap-nas.sh. Review before applying.\n'
  local idx label mountpoint
  for idx in "${!DATA_DISK_LABELS[@]}"; do
    label="${DATA_DISK_LABELS[$idx]}"
    mountpoint="/mnt/disk$((idx + 1))"
    printf 'LABEL=%s %s btrfs %s 0 0\n' "$label" "$mountpoint" "$BTRFS_DATA_FSTAB_OPTS"
  done
  if ! is_placeholder "$PARITY_LABEL"; then
    printf 'LABEL=%s %s ext4 rw,noatime,nofail,x-systemd.device-timeout=10s 0 2\n' "$PARITY_LABEL" "$PARITY_MOUNT"
  fi
}

mount_unit_name_for_path() {
  local path="${1#/}"
  path="${path//\//-}"
  printf '%s.mount\n' "$path"
}

mergerfs_branch_list() {
  local suffix="$1"
  local branches=()
  local idx
  for idx in "${!DATA_DISK_LABELS[@]}"; do
    branches+=("/mnt/disk$((idx + 1))/$suffix")
  done
  IFS=:
  printf '%s' "${branches[*]}"
}

mergerfs_requires_mounts_for() {
  local requires=()
  local idx
  for idx in "${!DATA_DISK_LABELS[@]}"; do
    requires+=("/mnt/disk$((idx + 1))")
  done
  printf '%s ' "${requires[@]}"
}

generate_mergerfs_mount_unit_text() {
  local mountpoint="$1" branch_suffix="$2" options="$3"
  local what requires
  what="$(mergerfs_branch_list "$branch_suffix")"
  requires="$(mergerfs_requires_mounts_for)"
  cat <<UNIT
[Unit]
Description=mergerfs mount for $mountpoint
RequiresMountsFor=$requires

[Mount]
What=$what
Where=$mountpoint
Type=mergerfs
Options=$options

[Install]
WantedBy=local-fs.target
UNIT
}

generate_mergerfs_mount_units() {
  [[ "${#DATA_DISKS[@]}" -gt 0 ]] || return 0
  local data_unit snapshot_unit data_text snapshot_text
  data_unit="$(target_path "/etc/systemd/system/$(mount_unit_name_for_path "$MERGERFS_MOUNT")")"
  snapshot_unit="$(target_path "/etc/systemd/system/$(mount_unit_name_for_path "$SNAPSHOT_VIEW_MOUNT")")"
  data_text="$(generate_mergerfs_mount_unit_text "$MERGERFS_MOUNT" pool "defaults,cache.files=off,use_ino,ignorepponrename=true,category.create=$MERGERFS_CREATE_POLICY,moveonenospc=true,minfreespace=$MERGERFS_MIN_FREE_SPACE")"
  snapshot_text="$(generate_mergerfs_mount_unit_text "$SNAPSHOT_VIEW_MOUNT" snapshots "defaults,ro,cache.files=off")"
  write_text "$data_unit" "$data_text"
  write_text "$snapshot_unit" "$snapshot_text"
  if [[ "$APPLY" == true ]]; then
    target_run systemctl enable "$(mount_unit_name_for_path "$MERGERFS_MOUNT")" "$(mount_unit_name_for_path "$SNAPSHOT_VIEW_MOUNT")"
  fi
}

replace_managed_block() {
  local path="$1"
  local block="$2"
  local name="$3"
  local begin="# BEGIN $name managed block"
  local end="# END $name managed block"
  log "+ update managed block in $path"
  [[ "$APPLY" == true ]] || return 0

  local tmp
  tmp="$(mktemp)"
  if [[ -f "$path" ]]; then
    awk -v begin="$begin" -v end="$end" '
      $0 == begin { skip=1; next }
      $0 == end { skip=0; next }
      !skip { print }
    ' "$path" >"$tmp"
  fi
  {
    sed -e '${/^$/d;}' "$tmp"
    if [[ -s "$tmp" ]]; then
      printf '\n\n'
    fi
    printf '%s\n%s\n%s\n' "$begin" "$block" "$end"
  } >"$path"
  rm -f "$tmp"
}

generate_fstab_file() {
  local output="$STAGING_DIR/fstab.generated"
  local text
  text="$(generate_fstab_text)"
  log "Generating fstab at $output"
  printf '%s' "$text" >"$output"
  if [[ "$APPLY" == true ]]; then
    local target_fstab
    target_fstab="$(target_path /etc/fstab)"
    backup_file "$target_fstab"
    replace_managed_block "$target_fstab" "$text" nas-bootstrap
  fi
}

mount_target_fstab() {
  if [[ "$TARGET_MODE" == "live" ]]; then
    mount_live_mergerfs_explicit
  else
    run mount -a
    target_run systemctl start "$(mount_unit_name_for_path "$MERGERFS_MOUNT")" "$(mount_unit_name_for_path "$SNAPSHOT_VIEW_MOUNT")"
  fi
}

perform_mount_ops_now() {
  [[ "$APPLY" == true || "$CHECK_LIVE_TARGET" == true ]]
}

unmount_all_at_path() {
  local path="$1"
  local attempts=0

  while findmnt -rn --mountpoint "$path" >/dev/null 2>&1; do
    attempts=$((attempts + 1))
    if (( attempts > 10 )); then
      die "could not unmount all existing mounts at $path"
    fi
    log "+ umount -l $(printf '%q' "$path")"
    if perform_mount_ops_now; then
      umount -l "$path"
    fi
    sleep 0.2
  done
}

assert_single_mount_at_path() {
  local path="$1"
  local count
  count="$(findmnt -rn -o TARGET 2>/dev/null | awk -v path="$path" '$0 == path { count++ } END { print count + 0 }')"
  [[ "$count" -eq 1 ]] || die "$path should have exactly one mount, found $count"
}

path_has_transport_endpoint_error() {
  local path="$1"
  local err
  err="$(ls "$path" 2>&1 >/dev/null || true)"
  [[ "$err" == *"Transport endpoint is not connected"* ]]
}

mount_live_mergerfs_explicit() {
  local pool_branches=()
  local snapshot_branches=()
  local idx final_mountpoint active_mountpoint joined_pool joined_snapshot
  for idx in "${!DATA_DISK_LABELS[@]}"; do
    final_mountpoint="/mnt/disk$((idx + 1))"
    active_mountpoint="$(active_mount_path "$final_mountpoint")"
    pool_branches+=("$active_mountpoint/pool")
    snapshot_branches+=("$active_mountpoint/snapshots")
  done
  joined_pool="$(
    IFS=:
    printf '%s' "${pool_branches[*]}"
  )"
  joined_snapshot="$(
    IFS=:
    printf '%s' "${snapshot_branches[*]}"
  )"

  local active_pool_mount active_snapshot_mount mergerfs_bin mergerfs_lib_path data_opts snapshot_opts
  active_pool_mount="$(active_mount_path "$MERGERFS_MOUNT")"
  active_snapshot_mount="$(active_mount_path "$SNAPSHOT_VIEW_MOUNT")"
  mergerfs_bin="$TARGET_ROOT/usr/bin/mergerfs"
  mergerfs_lib_path="$TARGET_ROOT/usr/lib"
  data_opts="defaults,cache.files=off,use_ino,ignorepponrename=true,category.create=$MERGERFS_CREATE_POLICY,moveonenospc=true,minfreespace=$MERGERFS_MIN_FREE_SPACE"
  snapshot_opts="defaults,ro,cache.files=off"

  ensure_dir "$active_pool_mount"
  ensure_dir "$active_snapshot_mount"

  if perform_mount_ops_now; then
    [[ -x "$mergerfs_bin" ]] || die "target mergerfs binary not found or not executable: $mergerfs_bin"
    unmount_all_at_path "$active_pool_mount"
    unmount_all_at_path "$active_snapshot_mount"
  fi

  log "+ LD_LIBRARY_PATH=$(printf '%q' "$mergerfs_lib_path") $(printf '%q' "$mergerfs_bin") -o $(printf '%q' "$data_opts") $(printf '%q' "$joined_pool") $(printf '%q' "$active_pool_mount")"
  if perform_mount_ops_now; then
    LD_LIBRARY_PATH="$mergerfs_lib_path${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
      "$mergerfs_bin" -o "$data_opts" "$joined_pool" "$active_pool_mount"
  fi

  log "+ LD_LIBRARY_PATH=$(printf '%q' "$mergerfs_lib_path") $(printf '%q' "$mergerfs_bin") -o $(printf '%q' "$snapshot_opts") $(printf '%q' "$joined_snapshot") $(printf '%q' "$active_snapshot_mount")"
  if perform_mount_ops_now; then
    LD_LIBRARY_PATH="$mergerfs_lib_path${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
      "$mergerfs_bin" -o "$snapshot_opts" "$joined_snapshot" "$active_snapshot_mount"
    assert_single_mount_at_path "$active_pool_mount"
    assert_single_mount_at_path "$active_snapshot_mount"
  fi
}

ensure_live_mergerfs_healthy() {
  [[ "$TARGET_MODE" == "live" ]] || return 0

  local active_data active_snapshots needs_remount=false
  active_data="$(active_mount_path "$MERGERFS_MOUNT")"
  active_snapshots="$(active_mount_path "$SNAPSHOT_VIEW_MOUNT")"

  if ! findmnt "$active_data" >/dev/null 2>&1; then
    needs_remount=true
  elif path_has_transport_endpoint_error "$active_data"; then
    needs_remount=true
  fi

  if ! findmnt "$active_snapshots" >/dev/null 2>&1; then
    needs_remount=true
  elif path_has_transport_endpoint_error "$active_snapshots"; then
    needs_remount=true
  fi

  if [[ "$needs_remount" == true ]]; then
    warn "Live mergerfs mounts missing or unhealthy; remounting active live mergerfs views."
    mount_live_mergerfs_explicit
  fi
}

verify_dir_exists() {
  local path="$1"
  [[ -d "$path" ]] || die "required directory missing after creation: $path"
}

verify_active_pool_visible() {
  local active_data subvol
  active_data="$(active_mount_path "$MERGERFS_MOUNT")"

  for subvol in "${POOL_SUBVOLUMES[@]}"; do
    [[ -d "$active_data/$subvol" ]] || die "$active_data/$subvol is missing after mergerfs mount"
  done
}

ensure_active_pool_permissions() {
  local active_data subvol
  active_data="$(active_mount_path "$MERGERFS_MOUNT")"
  run chown "$PUID:$PGID" "$active_data"
  run chmod 0775 "$active_data"
  for subvol in "${POOL_SUBVOLUMES[@]}"; do
    run chown "$PUID:$PGID" "$active_data/$subvol"
    run chmod 0775 "$active_data/$subvol"
  done
}

verify_active_pool_writable() {
  [[ "$VALIDATE_WRITE_TESTS" == "true" ]] || return 0
  local active_data test_path
  active_data="$(active_mount_path "$MERGERFS_MOUNT")"
  test_path="$active_data/.nas-bootstrap-write-test"

  touch "$test_path" || die "$active_data is not writable"
  rm -f "$test_path"
}

configure_storage() {
  log "Phase: storage, btrfs layout, and mergerfs"
  if ! target_command_available mergerfs; then
    warn "mergerfs command not found; install it before mounting /data."
  fi

  local idx
  for idx in "${!DATA_DISKS[@]}"; do
    if [[ "$idx" -lt "${#DATA_DISK_LABELS[@]}" ]]; then
      configure_data_disk "$((idx + 1))" "${DATA_DISKS[$idx]}" "${DATA_DISK_LABELS[$idx]}"
    fi
  done

  local active_parity_mount active_pool_mount active_snapshot_mount
  active_parity_mount="$(active_mount_path "$PARITY_MOUNT")"
  active_pool_mount="$(active_mount_path "$MERGERFS_MOUNT")"
  active_snapshot_mount="$(active_mount_path "$SNAPSHOT_VIEW_MOUNT")"

  ensure_safe_mountpoint "$active_parity_mount"
  if ! is_placeholder "$PARITY_DISK" && ! filesystem_matches "$PARITY_DISK" ext4 "$PARITY_LABEL"; then
    confirm_destructive "About to format the SnapRAID parity disk as ext4." "$PARITY_DISK"
    run mkfs.ext4 -F -L "$PARITY_LABEL" "$PARITY_DISK"
  fi
  if [[ "$APPLY" == true ]] && ! is_placeholder "$PARITY_DISK" && ! mountpoint -q "$active_parity_mount"; then
    run mount -o rw,noatime "$PARITY_DISK" "$active_parity_mount"
  fi

  ensure_safe_mountpoint "$active_pool_mount"
  ensure_safe_mountpoint "$active_snapshot_mount"
  generate_fstab_file
  generate_mergerfs_mount_units
  if [[ "$APPLY" == true ]]; then
    if [[ "$TARGET_MODE" == "host" ]]; then
      target_run findmnt --verify
      run systemctl daemon-reload
    else
      warn "TARGET_MODE=live: skipping systemctl daemon-reload in the live ISO"
    fi
    mount_target_fstab
    run findmnt "$active_pool_mount"
    run findmnt "$active_snapshot_mount"
    ensure_live_mergerfs_healthy
    verify_active_pool_visible
    ensure_active_pool_permissions
    verify_active_pool_writable
  fi
}
