configure_operations_basics() {
  log "Phase: journald limits and backup placeholders"
  ensure_dir "$(target_path /etc/systemd/journald.conf.d)"
  ensure_dir "$(target_path /usr/local/sbin)"
  backup_file "$(target_path /etc/systemd/journald.conf.d/90-nas-bootstrap.conf)"
  write_text "$(target_path /etc/systemd/journald.conf.d/90-nas-bootstrap.conf)" \
    "[Journal]"$'\n'"SystemMaxUse=$JOURNALD_SYSTEM_MAX_USE"$'\n'"RuntimeMaxUse=$JOURNALD_RUNTIME_MAX_USE"$'\n'"MaxRetentionSec=$JOURNALD_MAX_RETENTION_SEC"$'\n'
  backup_file "$(target_path /usr/local/sbin/nas-notify)"
  write_text "$(target_path /usr/local/sbin/nas-notify)" \
    "#!/usr/bin/env bash"$'\n'"set -euo pipefail"$'\n'"printf '[nas-notify] %s\n' \"\${*:-placeholder notification}\" >&2"$'\n'
  run chmod 0755 "$(target_path /usr/local/sbin/nas-notify)"
}

configure_firewall() {
  log "Phase: nftables firewall"
  if [[ "$FIREWALL_ENABLE" != "true" ]]; then
    warn "FIREWALL_ENABLE is false; skipping nftables policy generation."
    return 0
  fi

  local cidr cidr_csv="" has_cidr=false
  read -r -a firewall_cidrs <<<"${FIREWALL_LAN_CIDRS:-}"
  for cidr in "${firewall_cidrs[@]}"; do
    [[ -n "$cidr" ]] || continue
    has_cidr=true
    cidr_csv+="${cidr_csv:+, }$cidr"
  done
  [[ "$has_cidr" == true ]] || die "FIREWALL_LAN_CIDRS is empty"

  backup_file "$(target_path /etc/nftables.conf)"
  write_text "$(target_path /etc/nftables.conf)" "$(
    cat <<EOF
# Generated by NAS bootstrap
flush ruleset

table inet filter {
  set lan_cidrs {
    type ipv4_addr
    flags interval
    elements = { $cidr_csv }
  }

  chain input {
    type filter hook input priority 0; policy drop;
    iif "lo" accept
    ct state established,related accept
    ct state invalid drop
    ip protocol icmp accept
    ip6 nexthdr icmpv6 accept
    tcp dport 22 ip saddr @lan_cidrs accept
    tcp dport { 139, 445 } ip saddr @lan_cidrs accept
    udp dport { 137, 138 } ip saddr @lan_cidrs accept
  }

  chain forward {
    type filter hook forward priority 0; policy drop;
  }

  chain output {
    type filter hook output priority 0; policy accept;
  }
}
EOF
  )"

  if [[ "$APPLY" == true ]] && target_command_available nft; then
    target_run nft -c -f /etc/nftables.conf
  fi
}

configure_smartd() {
  log "Phase: smartmontools and smartd"
  if [[ "$SMART_ENABLE" != "true" ]]; then
    warn "SMART_ENABLE is false; skipping smartd configuration."
    return 0
  fi
  ensure_dir "$(target_path /etc)"
  backup_file "$(target_path /etc/smartd.conf)"
  write_text "$(target_path /etc/smartd.conf)" \
    "# DEVICESCAN is intentionally broad; unsupported QEMU virtio devices may not expose SMART."$'\n'"DEVICESCAN -a -o on -S on -n standby,q -M exec /usr/local/sbin/nas-notify smartd"$'\n'
}

configure_snapraid() {
  log "Phase: SnapRAID config and timers"
  if ! target_command_available snapraid; then
    warn "snapraid command not found; install it before enabling timers."
  fi
  copy_with_backup "$NAS_ROOT/config/snapraid.conf.example" "$(target_path /etc/snapraid.conf)"
  ensure_dir "$(target_path /var/lib/snapraid)"
  run chown root:root "$(target_path /var/lib/snapraid)"
  run chmod 0755 "$(target_path /var/lib/snapraid)"
  local unit
  for unit in snapraid-sync.service snapraid-sync.timer snapraid-scrub.service snapraid-scrub.timer; do
    copy_with_backup "$NAS_ROOT/config/systemd/$unit" "$(target_path "/etc/systemd/system/$unit")"
  done
  warn "SnapRAID sync is not started automatically. Review deletion guard TODO first."
}

configure_btrbk() {
  log "Phase: btrbk config and timer"
  copy_with_backup "$NAS_ROOT/config/btrbk.conf.example" "$(target_path /etc/btrbk/btrbk.conf)"
  local unit
  for unit in btrbk.service btrbk.timer; do
    copy_with_backup "$NAS_ROOT/config/systemd/$unit" "$(target_path "/etc/systemd/system/$unit")"
  done
}

configure_docker() {
  log "Phase: Docker directories and /data dependency"
  local active_data active_docker_root active_compose active_appdata
  active_data="$(active_mount_path "$MERGERFS_MOUNT")"
  active_docker_root="$(target_path "$DOCKER_ROOT")"
  active_compose="$(target_path "$DOCKER_COMPOSE_DIR")"
  active_appdata="$(target_path "$DOCKER_APPDATA_DIR")"
  if [[ "$TARGET_MODE" == "live" ]]; then
    ensure_live_mergerfs_healthy
  fi
  if [[ "$APPLY" == true ]] && ! findmnt -n "$active_data" >/dev/null 2>&1; then
    die "$active_data must be mounted before Docker setup"
  fi
  ensure_dir "$active_docker_root"
  ensure_dir "$active_compose"
  ensure_dir "$active_appdata"
  if [[ "$APPLY" == true ]]; then
    verify_dir_exists "$active_docker_root"
    verify_dir_exists "$active_compose"
    verify_dir_exists "$active_appdata"
  fi
  run chown -R "$PUID:$PGID" "$active_docker_root"
  backup_file "$(target_path /etc/systemd/system/docker.service.d/wait-for-data.conf)"
  write_text "$(target_path /etc/systemd/system/docker.service.d/wait-for-data.conf)" \
    "[Unit]"$'\n'"RequiresMountsFor=$MERGERFS_MOUNT"$'\n'"After=network-online.target"$'\n'"Wants=network-online.target"$'\n'
  copy_with_backup "$NAS_ROOT/config/docker-daemon.json.example" "$(target_path /etc/docker/daemon.json)"
}

configure_samba() {
  log "Phase: Samba config"
  copy_with_backup "$NAS_ROOT/config/smb.conf.example" "$(target_path /etc/samba/smb.conf)"
  if target_command_available testparm; then
    target_run testparm -s /etc/samba/smb.conf
  else
    warn "testparm not found; install samba before health checks."
  fi
}

configure_tailscale() {
  log "Phase: SSH and Tailscale"
  warn "Tailscale auth keys are not stored in this repo."
  log "Manual next step after service enablement: sudo tailscale up"
}

configure_services() {
  configure_operations_basics
  configure_firewall
  configure_smartd
  configure_snapraid
  configure_btrbk
  configure_docker
  configure_samba
  configure_tailscale
}

enable_services() {
  log "Phase: enable services"
  if [[ "$TARGET_MODE" == "host" ]]; then
    run systemctl daemon-reload
  else
    warn "TARGET_MODE=live: enabling target services only; not starting services inside chroot."
  fi
  if [[ "$FIREWALL_ENABLE" == "true" ]]; then
    target_run systemctl enable nftables
    if [[ "$START_SERVICES" == true && "$TARGET_MODE" == "host" ]]; then
      target_run systemctl start nftables
    fi
  fi
  target_run systemctl enable systemd-timesyncd.service
  if [[ "$START_SERVICES" == true && "$TARGET_MODE" == "host" ]]; then
    target_run systemctl start systemd-timesyncd.service
  fi
  if [[ "$SMART_ENABLE" == "true" ]]; then
    target_run systemctl enable smartd.service
    if [[ "$START_SERVICES" == true && "$TARGET_MODE" == "host" ]]; then
      target_run systemctl start smartd.service
    fi
  fi
  if [[ "$DOCKER_ENABLE" == "true" ]]; then
    target_run systemctl enable docker
    if [[ "$START_SERVICES" == true && "$TARGET_MODE" == "host" ]]; then
      target_run systemctl start docker
    fi
  fi
  if [[ "$TAILSCALE_ENABLE" == "true" ]]; then
    target_run systemctl enable sshd tailscaled
    if [[ "$START_SERVICES" == true && "$TARGET_MODE" == "host" ]]; then
      target_run systemctl start sshd tailscaled
    fi
  else
    target_run systemctl enable sshd
  fi
  if [[ "$SMB_ENABLE" == "true" ]]; then
    target_run systemctl enable smb nmb
    if [[ "$START_SERVICES" == true && "$TARGET_MODE" == "host" ]]; then
      target_run systemctl start smb nmb
    fi
  fi
  if [[ "$SNAPRAID_ENABLE" == "true" ]]; then
    target_run systemctl enable snapraid-sync.timer snapraid-scrub.timer
  fi
  if [[ "$BTRBK_ENABLE" == "true" ]]; then
    target_run systemctl enable btrbk.timer
  fi
  if [[ "$SNAPPER_ENABLE" == "true" ]]; then
    target_run systemctl enable snapper-timeline.timer snapper-cleanup.timer
    if [[ "$START_SERVICES" == true && "$TARGET_MODE" == "host" ]]; then
      target_run systemctl start snapper-timeline.timer snapper-cleanup.timer
    fi
  fi
  if [[ "$GRUB_BTRFS_ENABLE" == "true" ]]; then
    if [[ "$APPLY" != true ]] || target_unit_exists grub-btrfsd.service; then
      target_run systemctl enable grub-btrfsd.service
      if [[ "$START_SERVICES" == true && "$TARGET_MODE" == "host" ]]; then
        target_run systemctl start grub-btrfsd.service
      fi
    else
      warn "grub-btrfsd.service is not available; GRUB snapshot menu auto-refresh will not be enabled."
    fi
  fi
}

post_install_next_steps_text() {
  cat <<EOF
Set passwords before rebooting:

  arch-chroot $TARGET_ROOT passwd
  arch-chroot $TARGET_ROOT passwd $NAS_USER

Then run:

  sudo $SCRIPT_DIR/bootstrap-nas.sh --env-file $ENV_FILE --check-live-target

Then reboot without the ISO and run:

  sudo $SCRIPT_DIR/bootstrap-nas.sh --env-file $ENV_FILE --check-health
EOF
}

write_post_install_next_steps() {
  [[ "$INSTALL_ARCH" == true ]] || return 0
  local path="$TARGET_ROOT/root/NAS_POST_INSTALL_NEXT_STEPS.txt"
  log "+ write $path"
  if [[ "$APPLY" == true ]]; then
    mkdir -p "$TARGET_ROOT/root"
    post_install_next_steps_text >"$path"
  fi
}

print_post_install_password_reminder() {
  [[ "$INSTALL_ARCH" == true ]] || return 0
  cat <<EOF
================================================================================
IMPORTANT NEXT STEP: SET PASSWORDS BEFORE REBOOTING
================================================================================

The installed system was created, but passwords may not be set yet.

Run these before rebooting out of the Arch ISO:

  arch-chroot $TARGET_ROOT passwd
  arch-chroot $TARGET_ROOT passwd $NAS_USER

Then run the pre-reboot live target check:

  sudo $SCRIPT_DIR/bootstrap-nas.sh \\
    --env-file $ENV_FILE \\
    --check-live-target

Only reboot after passwords and the live target check are done.

After rebooting without the ISO, run:

  sudo $SCRIPT_DIR/bootstrap-nas.sh \\
    --env-file $ENV_FILE \\
    --check-health

================================================================================
EOF
}

CHECK_PASS=0
CHECK_WARN=0
